# Generated by Django 6.1.1 on 2026-09-06 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('combos', 'Combos'), ('pollo', 'Pollo'), ('papas', 'Papas'), ('bebidas', 'Bebidas'), ('otros', 'Otros')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('controla_stock', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('es_combo', models.BooleanField(default=False)),
                ('combo_incluye', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('enviada', 'Enviada a cocina'), ('entregada', 'Entregada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_a_cocina', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto')),
            ],
        ),
    ]
