# Generated by Django 6.1.1 on 2026-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_registroaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requiere_pieza',
            field=models.BooleanField(default=False),
        ),
    ]
