# Generated by Django 6.1.1 on 2026-09-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_producto_requiere_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, upload_to='productos/'),
        ),
    ]
