# Generated by Django 6.1.1 on 2026-09-11 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='acompanamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pedidos.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='acompanamiento_incluido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('combos', 'Combos'), ('pollo', 'Pollo'), ('papas', 'Papas'), ('acompanamientos', 'Acompañamientos'), ('bebidas', 'Bebidas'), ('otros', 'Otros')], max_length=20),
        ),
    ]
