# Generated by Django 6.1.1 on 2026-09-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_acompanamientos_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('combos', 'Combos'), ('pollo', 'Pollo'), ('acompanamientos', 'Acompañamientos'), ('bebidas', 'Bebidas'), ('gaseosas', 'Gaseosas'), ('otros', 'Otros')], max_length=20),
        ),
    ]
