# Generated by Django 6.1.1 on 2026-09-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_categoria_gaseosas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='listo_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
