# Generated by Django 6.1.1 on 2026-09-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_quitar_categoria_otros'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='sin_acompanamientos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orden',
            name='es_venta_directa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='para_llevar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='opciones_incluidas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
