# Generated by Django 6.1.1 on 2026-09-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_detalleorden_sin_acompanamientos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezaPollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('orden', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='variantes_elegidas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('opciones', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='pedidos.producto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
