# Generated by Django 6.1.1 on 2026-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_piezapollo_detalleorden_variantes_elegidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMenestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
