# Generated by Django 6.1.1 on 2026-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='despresado',
            field=models.BooleanField(default=False),
        ),
    ]
