# Generated by Django 6.1.1 on 2026-09-13 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_detalleorden_despresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='cuenta',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('cerrada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='pedidos.mesa')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('mesa', 'numero')},
            },
        ),
    ]
