# Generated by Django 6.1.1 on 2026-09-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_detalleorden_cuenta_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuentaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.PositiveIntegerField(default=1)),
                ('listo', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_estado', to='pedidos.orden')),
            ],
            options={
                'unique_together': {('orden', 'cuenta')},
            },
        ),
    ]
