# Generated by Django 6.1.1 on 2026-09-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_estadocuentaorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('pollo', 'Pollo'), ('papa', 'Papa'), ('vegetales', 'Vegetales'), ('aceite', 'Aceite'), ('condimentos', 'Condimentos'), ('bebidas', 'Bebidas y gaseosas'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dia_mes', models.PositiveSmallIntegerField(default=1, help_text='Dia del mes en que se genera (1-28, para que sirva en todos los meses).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='pedidos.gastorecurrente'),
        ),
    ]
