# Generated by Django 6.1.1 on 2026-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_gastorecurrente_gasto_recurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastorecurrente',
            name='tipo',
            field=models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('internet', 'Internet'), ('alquiler', 'Alquiler'), ('sueldos', 'Sueldos'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
