# Generated by Django 6.1.1 on 2026-09-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_gastorecurrente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastorecurrente',
            name='dia_mes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Dia del mes en que se genera (1-31). Si el mes no llega a ese dia (ej: 31 en abril, o 30/31 en febrero) se genera el ultimo dia de ese mes.'),
        ),
    ]
