# Generated by Django 6.1.1 on 2026-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_alter_gastorecurrente_dia_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
