# Generated by Django 6.1.1 on 2026-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_producto_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('enviada', 'Enviada a cocina'), ('lista', 'Lista para entregar'), ('entregada', 'Entregada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20),
        ),
    ]
