# Generated by Django 6.1.1 on 2026-09-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_variantes_combo_arroz_menestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('personal', 'Personal'), ('litro', 'De litro'), ('litro_35', 'De 1.35 litros'), ('dos_litros', 'De 2 litros')], default='personal', max_length=20),
        ),
    ]
