# Generated by Django 6.1.1 on 2026-09-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_asignar_tamano_gaseosas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='para_llevar',
        ),
        migrations.AddField(
            model_name='estadocuentaorden',
            name='para_llevar',
            field=models.BooleanField(default=False),
        ),
    ]
