# Generated by Django 6.1.1 on 2026-09-17 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_remove_orden_para_llevar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.piezapollo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_piezas', to='pedidos.producto')),
            ],
            options={
                'unique_together': {('producto', 'pieza')},
            },
        ),
    ]
