"""
Django settings for restaurante project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Si hay DATABASE_URL, asumimos que corremos en Vercel (produccion).
DATABASE_URL = os.environ.get('DATABASE_URL')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En Vercel: definir SECRET_KEY como variable de entorno (obligatorio en produccion).
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-kvv9j1#q(2(i5c&pniecl2@5*s4(ts@p+kbgs^sv7n+6-hgq6$',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Local (sin DATABASE_URL): DEBUG=True por defecto. En Vercel: False por defecto
# (se puede forzar con la variable de entorno DEBUG=True/False).
DEBUG = os.environ.get('DEBUG', 'False' if DATABASE_URL else 'True') == 'True'

# Para probar en local: correr con `python manage.py runserver 0.0.0.0:8000`
# y abrir esa IP desde las tablets conectadas a la misma WiFi.
ALLOWED_HOSTS = ['*']

# Necesario para que Django confie en el dominio de Vercel al validar CSRF (POST de login,
# pedidos, etc.) ya que se sirve por HTTPS detras de un proxy.
CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'pedidos',
]
# ojo: 'cloudinary_storage' (el paquete django-cloudinary-storage) a proposito NO esta en
# INSTALLED_APPS. Solo usamos su clase MediaCloudinaryStorage (import normal, no necesita
# ser app) para las fotos de producto; si se registra como app, su propio 'collectstatic'
# reemplaza al de Django y deja de copiar los estaticos (CSS, iconos) al hacer deploy.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurante.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pedidos.context_processors.css_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurante.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL, conn_max_age=600, ssl_require=True
        )
    }
else:
    # Local (sin DATABASE_URL): sqlite, como siempre.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fotos de productos subidas desde /admin/
# En Vercel el filesystem es de solo lectura salvo /tmp, asi que las fotos no se pueden
# guardar ahi: si CLOUDINARY_CLOUD_NAME esta seteado, se suben a Cloudinary en su lugar.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# Django 6 ya no lee DEFAULT_FILE_STORAGE/STATICFILES_STORAGE (settings viejos):
# hay que armar STORAGES a mano. Los estaticos (CSS, iconos) siempre quedan con el
# backend normal de Django/Vercel; solo el storage "default" (media) cambia a Cloudinary
# cuando hay credenciales.
STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.MediaCloudinaryStorage'
            if CLOUDINARY_STORAGE['CLOUD_NAME']
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Login / roles
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'post_login'

CSRF_FAILURE_VIEW = 'pedidos.views.csrf_failure'
